Ordinamento.exe: Ordina.o MainOrdina.o
	g++ -o Ordina.exe Ordina.o MainOrdina.o

Ordina.o: Ordina.cpp Ordina.hpp
	g++ -c -Wall Ordina.cpp

MainOrdina.o: MainOrdina.cpp Ordina.hpp
	g++ -c -Wall MainOrdina.cpp